### ISSUE TITLE
Google analytics does not activate

### ISSUE THREAD

**Issue by luiscantero** [GiovanniSalmeri/yellow-analytics#1]
There seems to be an issue with using Google analytics:
* `analytics.php` passes the config property `analyticsGoogleAnalytics` as a JS object called `google`
* `analytics.js` -> `disableTracking` accesses the property `this.config.google` correctly
* Problem: `analytics.js` -> `activateTracking` uses `this.tracking.AnalyticsCode` to activate Google tracking, but the property `tracking` does not exist
* I looked at the [original code](https://github.com/manucaralmo/GlowCookies/blob/master/src/glowCookies.js) and it seems to be different, even though it has the same version number. For example it does create an object called `this.tracking.AnalyticsCode` but it expects a property called `analytics` and not `google`.

From what I've seen: to solve the issue you would need to update the JS file to the latest version and update the PHP file to pass the property `analytics` instead of `google` . Or else update the JS file accordingly.

Update: I just noticed an additional issue that happens if you use the updated analytics.js file - the PHP file calls `glowCookies.start(object)` ... but the start method actually expects `(language, object)`, so that would need to be updated as well. Now it works in my environment.

Thanks.

**Comment by GiovanniSalmeri** [comment]
Thank you very much! I will fix these issues as soon as possible.

**Comment by GiovanniSalmeri** [comment]
In fact I refactored (also for simplicity) the original code of glowCookies, but I forgot to rename that variable. I hope that with the last commit it works. As regards the variable (language), I suppressed it, because in this adaptation to Yellow the choice of the language is done by the PHP code. Thank you very much for taking the time of looking into it!

**Comment by luiscantero** [comment]
I tested it and it works, thanks a lot for the quick reaction!
